### PR TITLE
feat: add ScrambledBugs addresses

### PR DESCRIPTION
**Pull request by RafearTheModder**
Manually verified identical using Ghidra. Used name labels from my SE Ghidra environment for the "friendly name" column in the csv entries.

### CODE REVIEW

**Comment by alandtse** [comment]
Just to confirm, 4 means you confirmed the function is bit for bit identical so if someone were to hook within the function, there is no difference in offset. 3 would be if you confirmed it matches but the offset would need to change.

Lastly, does scrambledbugs provide any info on the function name/sig?

**Comment by RafearTheModder** [comment]
I looked through and each function I found in this PR matches in structure and logic exactly. Although some addresses referenced are different and that technically makes the bytestream different, that appears to only be because the data and functions pointed to have moved between SE and VR, as I would expect. Is the addresses moving like that enough that they should be marked as a 3 instead then?

I think Scrambled Bugs has information about the name in comments, but no details on the signature. Scrambled Bugs seemed much less worried about the functions in general than just the specific offset into them where RE::ApplyPerkEntries was being called so it can replace those specific calls with a custom function.

**Comment by alandtse** [comment]
Relative addresses for data is fine.  There's actually a ghidra matchers for exact instructions that is how I came up with the 4 confidence. It's primarily a signal that the VR code doesn't have to change offsets or anything and will work out of the box.

**Comment by RafearTheModder** [comment]
I have added the rest of the addresses I have found and discussed with you on discord, including the one that did not already have an ID. This marks the entirety of what I should need for the perk entry patch from Scrambled Bugs.

I also changed the name column for each address I started this PR with to use the better descriptive names taken from the Scrambled Bugs comments you asked about.

Is there anything else you want/need me to do before completing this PR?

**Comment by alandtse** [comment]
Awesome thanks. Doing a new release.

**Pull request merged**
