### PR TITLE
Add Actor::Bind for Papyrus Tweaks NG

### PR DESCRIPTION
**Pull request by Nightfallstorm**
This is used for the `IsHostileToActor` crash fix, tested and confirmed working on VR with this entry

### CODE REVIEW

**Comment by alandtse** [comment]
If it's been confirmed, can you update confidence to 3 instead of 2? If you've confirmed it's byte identical, you should make it 4. This let's tooling potentially flag stuff that may require changed offsets.

**Comment by Nightfallstorm** [comment]
It's a 3 because the offset is different in VR despite being the same function: REL::VariantOffset(0x2CA6, 0x2FDB, 0x2BA4)

I haven't confirmed if the logic is identical or not since it is a pretty huge function, so that is why it is a 2 currently.

**Comment by alandtse** [comment]
I'm about confused. Should it be 3 or 2? 3 is manual and automatic identification. 2 would be so manual only.

**Comment by Nightfallstorm** [comment]
It was identified manually by string matching. The function has a bunch of strings correlating to the Actor script class, which is how I matched it.

**Pull request merged**
