### PR TITLE
feat: Add addresses for PoachedBugs VR and AlchemyXPFix

### PR DESCRIPTION
**Pull request by RafearTheModder**
50461/RE::CraftingSubMenu::UpdateCraftingInfo is for AlchemyXPFix, all other addresses are for WIP PoachedBugs VR patches.

All have been verified with both Ghidra version tracking and BinDiff inspection on assembly.

### CODE REVIEW

**Comment by alandtse** [comment]
Thanks!

**Comment by alandtse** [comment]
Missed it earlier during review, but please properly escape long strings so it doesn't break CSV parsers. https://github.com/alandtse/skyrim_vr_address_library/pull/61/files#diff-3b5e7c8ffc26259d096c99099d8ba90d73c82613953dfde8638fdd6688b1646aR359

**Comment by RafearTheModder** [comment]
For clarity. is the problem with 33257 that you are pointing out the length, or the presence of commas without being wrapped in quotes, or both? Because I see that some other lines in the database file that I have are even longer than that one, like ID 33632 for example.

Also this prompting me to look at the file made me realize that there are now duplicate lines for 33257 and 33277, even though this appears to be harmless. I suspect there was an unnoticed mishap with a merge somewhere.

**Comment by alandtse** [comment]
Lack of quotes. Length is fine as long as quoted.

**Pull request merged**
